ALTER TABLE "Project" ADD COLUMN "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE "Project" ADD COLUMN "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE "UserToProject" ADD COLUMN "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW();